const challenges = [
    {
        challenge_name: "5.000 steps in one day",
        xp: 50,
        completed: false,
        challenge_description: "Walk 5.000 steps in one day",
        challenge_goal: 5000,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "100 steps in one day",
        xp: 150,
        completed: false,
        challenge_description: "Walk 100 steps in one day",
        challenge_goal: 100,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "100 steps in one day",
        xp: 150,
        completed: false,
        challenge_description: "Walk 100 steps in one day",
        challenge_goal: 100,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "100 steps in one day",
        xp: 150,
        completed: false,
        challenge_description: "Walk 100 steps in one day",
        challenge_goal: 100,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "100 steps in one day",
        xp: 150,
        completed: false,
        challenge_description: "Walk 100 steps in one day",
        challenge_goal: 100,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "100 steps in one day",
        xp: 150,
        completed: false,
        challenge_description: "Walk 100 steps in one day",
        challenge_goal: 100,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "100 steps in one day",
        xp: 150,
        completed: false,
        challenge_description: "Walk 100 steps in one day",
        challenge_goal: 100,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "1000 steps in one week",
        xp: 150,
        completed: false,
        challenge_description: "Walk 1000 steps in one day",
        challenge_goal: 1000,
        duration: "week",
        type: "steps",
    },
    {
        challenge_name: "100000 steps in one month",
        xp: 150,
        completed: false,
        challenge_description: "Walk 1000 steps in one month",
        challenge_goal: 100000,
        duration: "month",
        type: "steps",
    },

];

export default challenges;