const demo_challenges = [
    {
        challenge_name: "Demo challenge 1",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 1 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 2",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 2 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 3",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 3 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 4",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 4 description",
        challenge_goal: 0.1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 5",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 5 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 6",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 6 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 7",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 7 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 8",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 8 description",
        challenge_goal: 0.1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 9",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 9 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 10",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 10 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 11",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 11 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 12",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 12 description",
        challenge_goal: 0.1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 13",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 13 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 14",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 14 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 15",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 15 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 16",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 16 description",
        challenge_goal: 0.1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 17",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 17 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 18",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 18 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 19",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 19 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 20",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 20 description",
        challenge_goal: 0.1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 21",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 21 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 22",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 22 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 23",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 23 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 24",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 24 description",
        challenge_goal: 0.1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 25",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 25 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 26",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 26 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 27",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 27 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 28",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 28 description",
        challenge_goal: 0.1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 29",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 29 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 30",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 30 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 31",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 31 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 32",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 32 description",
        challenge_goal: 0.1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 33",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 33 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 34",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 34 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 35",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 35 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 36",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 36 description",
        challenge_goal: 0.1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 37",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 37 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 38",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 38 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 39",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 39 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 40",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 40 description",
        challenge_goal: 0.1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 41",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 41 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 42",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 42 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 43",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 43 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 44",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 44 description",
        challenge_goal: 0.1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 45",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 45 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 46",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 46 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 47",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 47 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 48",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 48 description",
        challenge_goal: 0.1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 49",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 49 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
    {
        challenge_name: "Demo challenge 50",
        xp: 150,
        completed: false,
        challenge_description: "Demo challenge 50 description",
        challenge_goal: 1,
        duration: "day",
        type: "steps",
    },
];

export default demo_challenges;
